apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-users
  namespace: ch
data:
  users.xml: |
    <yandex>
      <users>
        <ch_user>
          <password>test123</password>
          <grants>
            <grant>ALL ON *.*</grant>
          </grants>
        </ch_user>
      </users>
    </yandex>
