apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: ch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: yandex/clickhouse-server
          ports:
            - containerPort: 8123
            - containerPort: 9000
          volumeMounts:
            - name: clickhouse-users
              mountPath: /etc/clickhouse-server/users.d
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: clickhouse-users
          configMap:
            name: clickhouse-users
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-pv-claim
