apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv-volume
  labels:
    type: local
    app: clickhouse
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/clickhouse/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pv-claim
  namespace: ch
  labels:
    app: clickhouse
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
