apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: ch 
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8123
    targetPort: 8123
  - name: tcp
    port: 9000
    targetPort: 9000
  selector:
    app: clickhouse
