apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
            #- mountPath: /docker-entrypoint-initdb.d
            #  name: init-script
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        #- name: init-script
        #  configMap:
        #    name: postgres-init-script
